<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; color: #0F172A; font-size: 12px; }
        .header { border-bottom: 3px solid #0E7490; padding-bottom: 10px; margin-bottom: 16px; }
        .header h1 { margin: 0; font-size: 20px; color: #0E7490; }
        .meta { color: #475569; font-size: 11px; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #F1F5F9; text-align: left; padding: 6px 8px; font-size: 11px; border-bottom: 2px solid #CBD5E1; }
        td { padding: 6px 8px; font-size: 11px; border-bottom: 1px solid #E2E8F0; }
        tr:nth-child(even) td { background: #F8FAFC; }
        .footer { margin-top: 20px; font-size: 9px; color: #94A3B8; text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h1>EvacTech — {{ $title }}</h1>
        <div class="meta">
            {{ $center->name }} · Barangay {{ $center->barangay->name ?? '' }}
            @if($from || $to) &nbsp;·&nbsp; {{ $from ?? 'Start' }} to {{ $to ?? 'Present' }} @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($headings as $h)<th>{{ $h }}</th>@endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>@foreach($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>
            @empty
                <tr><td colspan="{{ count($headings) }}">No records found for the selected range.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by {{ $generatedBy }} on {{ now()->format('M d, Y h:i A') }}</div>
</body>
</html>
